version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_ES"
      PYTHONPATH: /opt/odoo/custom/src/odoo
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "versys.odootea.com"
      traefik.enable: "true"
      traefik.domain: "versys.odootea.com"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:versys.odootea.com;Path:/web,/website/info;PathPrefix:/web/,/website/info/
      traefik.main-0.frontend.rule: Host:versys.odootea.com
      traefik.longpolling-0.frontend.rule: Host:versys.odootea.com;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.versys-16-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.versys-16-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.versys-16-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.versys-16-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.versys-16-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.versys-16-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.versys-16-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.versys-16-0-prod-main-0.rule: Host(`versys.odootea.com`)
      traefik.http.routers.versys-16-0-prod-main-0.service: versys-16-0-prod-main
      traefik.http.routers.versys-16-0-prod-main-0.middlewares:
        versys-16-0-prod-buffering, versys-16-0-prod-compress, versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-main-secure-0.rule: Host(`versys.odootea.com`)
      traefik.http.routers.versys-16-0-prod-main-secure-0.service: versys-16-0-prod-main
      traefik.http.routers.versys-16-0-prod-main-secure-0.middlewares:
        versys-16-0-prod-buffering, versys-16-0-prod-compress, versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.versys-16-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.versys-16-0-prod-longpolling-0.rule:
        Host(`versys.odootea.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.versys-16-0-prod-longpolling-0.service: versys-16-0-prod-longpolling
      traefik.http.routers.versys-16-0-prod-longpolling-0.middlewares: versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-longpolling-secure-0.rule:
        Host(`versys.odootea.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.versys-16-0-prod-longpolling-secure-0.service: versys-16-0-prod-longpolling
      traefik.http.routers.versys-16-0-prod-longpolling-secure-0.middlewares: versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.versys-16-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.liftcorp-12-0-prod-forbiddenCrawlers-0.rule:
        Host(`versys.odootea.com`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-0.service: versys-16-0-prod-main
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-0.middlewares:
        versys-16-0-prod-buffering, versys-16-0-prod-compress,
        versys-16-0-prod-forbid-crawlers, versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`versys.odootea.com`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-secure-0.service: versys-16-0-prod-main
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-secure-0.middlewares:
        versys-16-0-prod-buffering, versys-16-0-prod-compress,
        versys-16-0-prod-forbid-crawlers, versys-16-0-prod-forceSecure
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.versys-16-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
